### ISSUE TITLE
src_h in third quarantine rule is replaced (modified) to the same value!

### ISSUE THREAD

**Issue by alshaboti** [zeek/zeek-netcontrol#8]
Simple-client.py receives four rules to quarantine the host `127.0.0.2`.
```
NetControl::quarantine_host(127.0.0.2, 8.8.8.8, 127.0.0.3, 15sec);
```
The third one, however, seems to be strange as it replace `src_h=8.8.8.8` by `src_h=8.8.8.8`!
```

('### Response.type is : ', <ResponseType.AddRule: 3>)
{    'cid': 4L,
     'entity': {    'conn': None,
                    'flow': {    'dst_h': '127.0.0.2/32',
                                 'dst_m': None,
                                 'dst_p': None,
                                 'src_h': '8.8.8.8/32',
                                 'src_m': None,
                                 'src_p': ('53', '/udp')},
                    'ip': None,
                    'mac': None,
                    'ty': u'FLOW'},
     'expire': datetime.timedelta(0, 15),
     'id': u'4',
     'location': u'',
     'mod': {    'dst_h': None,
                 'dst_m': None,
                 'dst_p': None,
                 'redirect_port': None,
                 'src_h': '8.8.8.8',
                 'src_m': None,
                 'src_p': None},
     'out_port': None,
     'priority': 5L,
     'target': u'FORWARD',
     'ty': u'MODIFY'}
```
To be consistant with the other rules, I think flow src_h should be `127.0.0.3/32`.

**Comment by 0xxon** [comment]
Hi,

sorry for the really slow reply on this. This is desired behavior. As explained in the documentation at https://docs.zeek.org/en/master/scripts/base/frameworks/netcontrol/main.zeek.html#id-NetControl::quarantine_host, quarantine_host quaranties a host and does not allow ot to contact the Internet anymore. To explain this to an affected user,  it rewrites traffic to the default DNS server to point to a quarantined DNS server.

In this case, the default DNS server is assumed to be 8.8.8.8. The quarantine rule reroutes the traffic to go to 127.0.0.2 (the quarantine DNS) instead of going to 8.8.8.8

I am going to close this - please feel free to re-open in case you have more questions.
